org.gradle.jvmargs  = -Xmx3G
org.gradle.parallel = true
org.gradle.caching  = true

minecraft           = 26.3

archiveBaseName     = nnwit
group               = mcp.mobius.waila
majorVersion        = 21

# [rei, jei, emi]
recipeViewer        = none

badpackets          = 0.12.2
rei                 = 13.0.666
jei                 = 1.20.2-16.0.0.28
emi                 = 1.0.23+1.20.2

fabricLoader        = 0.19.5
fabricApi           = 0.161.0+26.3
modMenu             = 21.0.0
trEnergy            = 5.0.0

forge               = 66.0.9
neo                 = 26.3.0.22-beta

architectury        = 10.0.7
clothConfig         = 12.0.107

quiltLoader         = 0.24.0
qsl                 = 8.0.0-alpha.12+1.20.4
qfapi               = 9.0.0-alpha.7+0.96.11-1.20.4

spigotApi           = 1.18.2-R0.1-SNAPSHOT
paperclip           = 1.18.2-313
